### ISSUE TITLE
Policy System Update

### ISSUE THREAD

**Issue by Soyvolon** [501stLegionA3/FiveOhFirstDataCore#103]
# Description
Update the website policy system to work with the `IWebsiteSettingsService` and support dynamic policy creation from the website.

# Details
- Each protected region would have a policy manager that website managers can use to select the policy that governs that protected region. 
- Global policies can be set from a manager page.
- Website settings service would need to include the Discord Role Bindings and CShop Claims bindings
- Any code that uses the static CShop Claims bindings would need to be converted to use the website settings service
    - This is the big push for updating the policy system, as the current functions can not access the service to make checks against the database.

# Notes
~~If done properly, none of the `<AuthorizeView>` blocks will need to be changed.~~

- Any checks that are done via code need to be removed, **or a custom method for dynamic checks needs to be made with the website settings service.**
- `<AuthorizeView>` elements need to be replaced with custom components that handle the building of the policy strings and passing them to the `<AuthorizeView>` or passing the default policy.

# Process Steps
## On application load
1. Pull all saved configuration data from the database
2. Build `WebsiteSettingsAuthorizationPolicyBuilder` for saved configuration
3. Cache all built policies for use in `DataCoreAuthorizationPolicyProvider`

## On navigation to pages with Authorize Views
1. Build a fully qualified page identifier
    a. Combine full navigation path with a custom provided name in the following format: `path/custom name`
    b. Use the page identifier to get the dynamic policy that has been assigned to that page.
2. Have the `DataCoreAuthorizationPolicyProvider` check against the dynamic policies, otherwise set the permissions to the manager only.

## On Update Policy
1. Update the database with the new requirements
2. Reload the cache

**Comment by power-5000** [comment]
Willing to take this on with some mentoring and guidance. This seems like one of the changes that should happen sooner rather than later for a lot of the pages so that we are redoing working in the future.

**Comment by Soyvolon** [comment]
Closed by #240
