### ISSUE TITLE
Razor Cmdr, Sub-Cmdr, FOIC cannot view access grants for pilots.

### ISSUE THREAD

**Issue by Zulu-87351** [501stLegionA3/FiveOhFirstDataCore#107]
# Describe the bug
Razor HQ cannot view Access Grants for any Pilots on the Access Grants page. 

# To Reproduce

# Expected behavior
Razor HQ is able to view access codes for any unregistered pilot in the unit.

# Screenshots
https://cdn.discordapp.com/attachments/721839363469738026/867812988500312094/unknown.png

# Platform
What browser and platform it is happening on. Ex: Firefox on the Google Pixel 4

# Notes
Any other notes go here.

**Comment by Soyvolon** [comment]
Due to the access grant page's being temporary for just the start of the website, and Kushi having access to roster clerk pages that show IDs, this won't be fixed.
