### ISSUE TITLE
Adding Qualification/MOS tracking for individual troopers

### ISSUE THREAD

**Issue by Stew-85996** [501stLegionA3/FiveOhFirstDataCore#11]
Would be helpful for SL/TL to be able to track trooper qualifications and requirements IOT ensure they are trained appropriately and MOS promotions are handed out on time.

**Comment by Soyvolon** [comment]
Qualification tracking has already been implemented.

Requirements for promotions can be implemented, will aim for the Phase 3

**Comment by jdoxley** [comment]
Was this implemented in #148? @Soyvolon

**Comment by Soyvolon** [comment]
Sort of - MOS promotion tracking needs operation counts (which need AARs) and is a lot longer down the way. But, promotion information is saved and able to be tracked.

Going to close this as the scope of tracking AARs and Operation counts is outside this issue.
