### ISSUE TITLE
Implement an EPAR module/system

### ISSUE THREAD

**Issue by power-5000** [501stLegionA3/FiveOhFirstDataCore#112]
# Description
EPAR stands for Electronic Personnel Action Requests, Essentially this system would allow individual troopers to request to the roster clerks/CoC for edits to their accounts, Example Corporal Waze notices that he isn't in the RTO Instructor C-Shop, this system would allow him to click a button and submit an "form" to the roster clerks that would say please do X.

# Details
I believe that this would streamline the process of correcting issues with trooper's accounts and allow the communication to happen quickly through the website rather than that individual having to find out who they need to contact and then contact them either via TS or discord.

**Comment by Soyvolon** [comment]
@Zulu-87351 any thoughts on how you would like this to be implemented?

**Comment by Zulu-87351** [comment]
@Soyvolon Pretty much as Power described. We already achieve this at present through a Google Form. Implementing this change will be a good thing. Suggestions I have are to make sure the request is field based with a reason field, ex. Change TiG to x because my promotion didnt update correctly.
