### ISSUE TITLE
Roster has overly long render time

### ISSUE THREAD

**Issue by M3ales** [501stLegionA3/FiveOhFirstDataCore#119]
## Describe the bug

Title

## To Reproduce

1. Go to Roster
2. Switch to Full Roster
3. Wait
4. Occasionally timeout (likely not happening in NA). Otherwise decently long (8-10 seconds typically)

## Expected behaviour

Page loads within 2-3 seconds.

## Screenshots

![image](https://user-images.githubusercontent.com/18268386/126884252-326d4674-c098-4629-934a-1184607be82e.png)

## Platform
- Chrome 91.0.4472.164

## Notes

So looking at [RosterService](https://github.com/501stLegionA3/FiveOhFirstDataCore/blob/e0684971b858510a56c01215e76df0f85f0d1d53/FiveOhFirstDataCore.Core/Services/RosterService.cs#L72):

```csharp
public async Task<List<Trooper>> GetFullRosterAsync()
{
    using var _dbContext = _dbContextFactory.CreateDbContext();
    List<Trooper> troopers = new();
    await _dbContext.Users.AsNoTracking().ForEachAsync(x =>
    {
        if (x.Slot < Data.Slot.Archived)
            troopers.Add(x);
    });

    return troopers;
}
```
AFAIK `.ForeachAsync` doesn't get translated to SQL as part of [LINQ-to-Entities](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/method-based-query-syntax-examples-filtering). Meaning you if there are 100 troopers it'll make 100 queries to postgres, instead of 1 query with a where clause.

If you replace that with:

```csharp
public async Task<List<Trooper>> GetFullRosterAsync()
{
    using var _dbContext = _dbContextFactory.CreateDbContext();
    return await _dbContext.Users.AsNoTracking().Where(trooper => trooper.Slot < Data.Slot.Archived).ToListAsync();
}
```

You should get significant improvements. I can explain further if it's still unclear.

**Comment by Soyvolon** [comment]
Very true, I had forgotten to go back and fix that.
