### ISSUE TITLE
Squad Leads not having all their squad codes

### ISSUE THREAD

**Issue by Dagwarrior** [501stLegionA3/FiveOhFirstDataCore#121]
At least for Acklay 1-2, SL does not have access codes for his TLs. and Lissy is not showing up in his codes either (as 1-2 Alpha medic)

**Comment by Soyvolon** [comment]
Can you confirm that Lissy is a.) slotted in the squad and b.) has not already registered?

**Comment by Soyvolon** [comment]
Just checked the site - Lissy has already registered their account. This is intended behavior.
