### ISSUE TITLE
NCOA Course Tracking

### ISSUE THREAD

**Issue by prophetthanatos** [501stLegionA3/FiveOhFirstDataCore#125]
# Description
Ability to add a NCOA course completion onto a trooper's entry with date of completion.

# Details
BLC/ALC/SLC/SSA/SMA/OCS, lock the ability to grant a pass to roster clerks and staff for respective courses (similar to qualifications presumably)

# Notes
BLC - Basic Leadership Course
ALC - Advanced Leadership Course
SLC - Senior Leadership Course
SSA - Senior Sergeant Academy
SMA - Sergeant Major Academy
OCS - Officer Candidate School

**Comment by Zulu-87351** [comment]
Most Likely Integrate into Phase 4 along with Qualifications.

**Comment by Soyvolon** [comment]
Maybe. Either way: @prophetthanatos the scope of this issue is too large, please break it down into separate parts.
