### ISSUE TITLE
Document new change conflict system for Roster Edit Page

### ISSUE THREAD

**Issue by Soyvolon** [501stLegionA3/FiveOhFirstDataCore#126]
# Pages Changed
- Roster Edit Page

# Detailed Changes
- When two edits to the same trooper occur at once, the system checks with edits are conflicting and displays a merge screen that lets changes be merged together.

**Comment by Zulu-87351** [comment]
Can you provide a picture of the page for dev. This is hard to replicate on the public tool.

**Comment by Soyvolon** [comment]
![image](https://user-images.githubusercontent.com/16871668/127167665-7ac94a65-ccd0-4044-b667-8f050854ef4e.png)
![image](https://user-images.githubusercontent.com/16871668/127167688-efef6809-3158-442a-8b07-ab9751564be4.png)
![image](https://user-images.githubusercontent.com/16871668/127167710-d515250b-dae8-4a59-a061-b3a8e93e9d4d.png)
![image](https://user-images.githubusercontent.com/16871668/127167740-ff0399ca-75ce-4aa8-bab0-35674fdf6bcf.png)
![image](https://user-images.githubusercontent.com/16871668/127167760-c55c2796-bca6-4de3-8ce3-f1b3985e9079.png)
![image](https://user-images.githubusercontent.com/16871668/127167777-e0227294-3d21-48c6-84e9-9aa7ed5349b9.png)
![image](https://user-images.githubusercontent.com/16871668/127167796-dcc716ef-aa85-41e8-a0bc-915c402ec460.png)
![image](https://user-images.githubusercontent.com/16871668/127167822-afd1db45-7d0e-472d-8ba8-1c05c990e47b.png)
![image](https://user-images.githubusercontent.com/16871668/127167868-ad127946-3661-468e-9621-40fb22f6d585.png)
![image](https://user-images.githubusercontent.com/16871668/127167888-6ec82fab-5667-41c4-8dc5-10c1934896f9.png)

**Comment by Soyvolon** [comment]
Once all conflicts have been resolved, and the accept merge button has been pressed, the save changes button becomes able to be pressed.

**Comment by Zulu-87351** [comment]
Should've closed with #154
