### ISSUE TITLE
Anonymous report filing

### ISSUE THREAD

**Issue by Stew-85996** [501stLegionA3/FiveOhFirstDataCore#13]
Option for troopers to submit informal complaints that are sent to company leadership with the battalion leadership being notified there was a complaint lodged in that company (but not what the issue was so that company level leadership is able to solve issues that don't need to be ran all the way up).

**Comment by prophetthanatos** [comment]
consider using the MPs for this function as well, either as a reporting/investigating body or a separate form altogether.
