### ISSUE TITLE
Consolidate unit filter options for Razor

### ISSUE THREAD

**Issue by bkroger2** [501stLegionA3/FiveOhFirstDataCore#140]
# Description
Consolidate Razor options in "Unit" filter box to display as (Razor HQ, Razor 1st Flight, Razor 2nd Flight, etc.)

# Details
Basically the goal here is to bring it more in line with how Warden HQ and their 3 sections are displayed in the filter 
For example. when "Razor 2nd Flight" is selected, then the below results should show up
- Flight Commander, both Section Leaders, all remaining pilots in that flight

I will be submitting a Roster Change form to have all Section Leaders' roles changed from Pilot to Section Leader

# Notes
If any questions or concerns, see CX Neb

**Comment by Soyvolon** [comment]
Filter options will not be consolidated. They are based off the roster data and is needed to put pilots in their correct position on the ORBAT and to determine where they are. If you want to filter a Razor unit, you can click the `T` icon to switch to text search and manually type in Razor 2 to see the information you would like to see.

![image](https://user-images.githubusercontent.com/16871668/127949375-b3cc4a0f-6d2d-44ba-8eb9-80023e336a8c.png)
