### ISSUE TITLE
Filter pilots by rank

### ISSUE THREAD

**Issue by bkroger2** [501stLegionA3/FiveOhFirstDataCore#141]
# Description
Add rank filters for all pilot ranks (Flight Cadet, Sr. Flight Cadet, Ensign, Sr. Ensign, Flight Officer, Lieutenant Jr. Grade)

# Details
Currently, all Flight Cadets and Sr. Flight Cadets are only filterable through the "Cadet" option. Razor would like to be able to distinguish them better from cadets who are not actually pilots. Additionally, no pilots with the rank of Ensign or higher can be filtered by rank as of current. This includes officers of 2nd LT+

# Notes
If any questions or concerns, see CX Neb

**Comment by Soyvolon** [comment]
You can filter by manually typing a rank by selecting the `T` and typing a rank in. I can see about filtering it by the Razor (and additional) rank values.
