### ISSUE TITLE
Possible Artist C Shop typo

### ISSUE THREAD

**Issue by jdoxley** [501stLegionA3/FiveOhFirstDataCore#156]
# Describe the bug
Unsure if it is meant to be `Artisan` or `Artist`

![image](https://user-images.githubusercontent.com/25972715/128621978-37057777-8395-410f-bfd0-f7c9b81b4370.png)

**Comment by Soyvolon** [comment]
Old C-Shop roster from the google sheet had them listed as Artisans. Internally, this will stay the same. See my comment on #157 about how we change change the display for this.
