### ISSUE TITLE
Corporal is Company level

### ISSUE THREAD

**Issue by ECloc** [501stLegionA3/FiveOhFirstDataCore#192]
# Describe the bug
Corporal is brought up to Battalion board.

# To Reproduce
1. Go to a promotion board
2. Promote a Sr. Trooper+ to Corporal
3. Board needed is only Company, unless Zeta.

# Expected behavior
Corporal should only require Company board.

# Screenshots
![image](https://user-images.githubusercontent.com/28656738/131229123-e05a7afe-1329-428e-be7f-da9954df765d.png)

# Platform
Chrome latest, modified.

# Notes
The [rank requirements document](https://docs.google.com/document/d/1lWFS24NWtfOKlM9YZByMLBOo3lZgLzE30_jpSOKCJZQ/edit?usp=sharing) has an extensive overview of all the rank requirements, their billet, and board requirements.

**Comment by Soyvolon** [comment]
Fixed.
