### ISSUE TITLE
Adding 4 trooper slots on every Zeta 1 squad

### ISSUE THREAD

**Issue by charl351** [501stLegionA3/FiveOhFirstDataCore#194]
Approved by zeta HQ, only on zeta section 1 squads (1-1,1-2,1-3,1-4). Just 4 trooper slots as well ty!

**Comment by Soyvolon** [comment]
Is that four additional trooper slots, or four trooper slots per team (eight in total)?

**Comment by charl351** [comment]
per squad, we dont have teams

**Comment by Soyvolon** [comment]
What is the total amount of troopers a Zeta 1 squad should have after this issue is resolved?

**Comment by charl351** [comment]
11

**Comment by Soyvolon** [comment]
Closed in `0ce48a3`
