### ISSUE TITLE
New Recruit Form does not check against current recuirt nicknames

### ISSUE THREAD

**Issue by Soyvolon** [501stLegionA3/FiveOhFirstDataCore#201]
# Describe the bug
The get in use user data method does not check any in use recruit data as recruits are listed in inactive reserves.

**Comment by power-5000** [comment]
GetInUseUserData should check Inactive Reserves though as those are still members of the unit and their names should not be allowed to be selected.

**Comment by Soyvolon** [comment]
No - recruiters only check against active names (anything not in inactive reserves). Birth numbers are checked unit wide.
