### ISSUE TITLE
Can't promote Troopers to Chief Warrant Officer on the Hailstorm board

### ISSUE THREAD

**Issue by Broad501** [501stLegionA3/FiveOhFirstDataCore#203]
You can't promote on other boards as well, but CW promotions only go on the Hailstorm board. If that might cause more harm than good you can make a CW-specific Promotion Board roster thingy and hide it under the Directories section.

**Comment by Soyvolon** [comment]
Can you confirm that you are unable to promote troopers to CW ranks with the manual promotion tool? Trooper to CW promotions are hidden from the eligibility listings.
