### ISSUE TITLE
Delete button for notice boards do not work

### ISSUE THREAD

**Issue by Soyvolon** [501stLegionA3/FiveOhFirstDataCore#209]
# Describe the bug
The delete button on the notice boards does not delete a notice board.

**Comment by power-5000** [comment]
Need further information. Dbcontext-NoticeBoards do not contain notices they are stored in DBcontext-Notices unsure of intended behavior.

**Comment by Soyvolon** [comment]
Notice boards - as in the one on the index page. Its not a problem with anything in the dbcontext, that is configured properly, its a problem with the `INoticeService` service implementation.
