### ISSUE TITLE
TiG on full roster is different than TiG on proflie page

### ISSUE THREAD

**Issue by Soyvolon** [501stLegionA3/FiveOhFirstDataCore#250]
# Describe the bug
These two displays need to show the same value.

**Comment by jdoxley** [comment]
This was fixed in #248 no?

**Comment by Soyvolon** [comment]
No. #248 only fixed the display position. The values are still different by 1 day.

**Comment by jdoxley** [comment]
I think I found the issue.
https://github.com/501stLegionA3/FiveOhFirstDataCore/blob/c221853cf17674f3288d36a5541577e51aa3f34f/FiveOhFirstDataCore.Pages/Roster/RosterListingRow.razor#L20-L25
https://github.com/501stLegionA3/FiveOhFirstDataCore/blob/c221853cf17674f3288d36a5541577e51aa3f34f/FiveOhFirstDataCore.Pages/Data/PublicTrooperProfile.razor.cs#L61-L67
When calculating the days it is using two different dates for `now`, which one would you prefer be used? @Soyvolon

**Comment by Soyvolon** [comment]
Yeah - that was the issue. We need to use `UtcNow` as that is what the values are saved in the database as.
