### ISSUE TITLE
Cyclone Company Directory

### ISSUE THREAD

**Issue by DimitriWest97** [501stLegionA3/FiveOhFirstDataCore#320]
Just a small issue where my name is not being displayed in the Cyclone Company Directory, instead just displaying TBD. Verified that Hailstorm directory does show correct information as well.
https://cdn.discordapp.com/attachments/826266620254355456/906753162034180116/9bc37e71a9218fda6ca3fbbcfb213d31.png

**Comment by Soyvolon** [comment]
Troopers can only hold one slot, you will not be displayed in multiple of them.
