### ISSUE TITLE
Razor promotion board entries not escalating properly

### ISSUE THREAD

**Issue by bkroger2** [501stLegionA3/FiveOhFirstDataCore#326]
# Describe the bug
Some promotions within Razor do not escalate up to the Battalion board as they should.

# To Reproduce
1. Go to 'Razor Promotion Board'
2. Start promotion request for any member
3. Select Rank of CX-S or higher
4. Promotion request shows that Razor board is highest required board for promotion approval

# Expected behavior
All pilots promoted to the rank of Lieutenant Jr. Grade (CX-S) and higher need to go through both the Razor and Battalion promotion boards

# Platform
All web browsers

# Notes
Direct any questions or concerns to CX Neb

**Comment by jdoxley** [comment]
This sounds like a configuration issue. Would need one of the managers to take a look at the promotion config.

**Comment by Soyvolon** [comment]
Needs code changes to properly raise values to battalion. For now, just make sure battalion is aware before hitting the promote button.
