### ISSUE TITLE
Warden Promotions' Escalation

### ISSUE THREAD

**Issue by Wirtimus** [501stLegionA3/FiveOhFirstDataCore#327]
# Describe the bug
Vet. Petty Officer escalating to Hailstorm Promotion Board

**Warden display information is not showing up on the Warden board, instead, it is showing up on the Hailstorm board.**

# To Reproduce
1. Go to  Hailstorm Board
2. Scroll down to Atom to Vet Petty Officer

# Expected behavior
Should only require approval on Warden Promotion Board

**Comment by Soyvolon** [comment]
Update: Added more error details.

**Comment by Wirtimus** [comment]
Error: Is on Hailstorm board. Should only require Warden Approval. Also cannot be approved by Battalion Staff while it is on the Hailstorm board. 
The lowest Warden rank that requires Council(Hailstorm) Approval is Chief Petty, every rank above that(Master Chief and Command Master Chief) also requires Council(Hailstorm) Approval.

**Comment by Soyvolon** [comment]
@Wirtimus I wasn't asking for more details - but thanks anyways. I was dropping a comment to let anyone know that I added an update to your original post with information about the real problem - the part in bold. For anyone picking this issue up, the edit is this: `Warden display information is not showing up on the Warden board, instead, it is showing up on the Hailstorm board.`

**Comment by Soyvolon** [comment]
Can't replicate this on the development side of things. Promotion to Vet. Petty Officer happens only in the Warden board.

**Comment by Soyvolon** [comment]
Closed in favor of #328
