### ISSUE TITLE
Razor Command is unable to promote Wardens

### ISSUE THREAD

**Issue by bkroger2** [501stLegionA3/FiveOhFirstDataCore#329]
# Describe the bug
Razor Command ( CO/XO/CLO ) are unable to promote Wardens.

# To Reproduce
1. Go to Warden Promotion Board as Razor CO/XO/CLO
2. Try to click on any Warden to promote
3. See inability to promote anyone

# Expected behavior
Razor Command should see the options to promote any Warden once they reach TiG for next rank, and should be able to start a manual promotion process.

# Platform
All web browsers

# Notes
Warden is a sub-detachment of Razor so both Warden leadership and Razor Command need the ability to promote anyone within the sub-detachment. See CX Neb with regarding any questions and/or concerns.

**Comment by Soyvolon** [comment]
Currently set so Commander and Sub Commander can promote wardens. Please let me know if anyone needs to be added or removed from that list of eligible promoters.
