### ISSUE TITLE
Birth number hyperlink in Razor Promotion Board redirects to wrong page

### ISSUE THREAD

**Issue by bkroger2** [501stLegionA3/FiveOhFirstDataCore#341]
# Describe the bug
When placing mouse cursor over the birth number for CX-C Bastil, the page shows that it's going to redirect the user to a trooper page that does not coincide with his actual birth number.

# To Reproduce
1. Go to Razor Promotion Board
2. Click on Birth Number for CX-C Bastil
3. See error

# Expected behavior
Should be redirected to the correct trooper page.

# Screenshots
https://imgur.com/a/EWhCJqg

# Platform
All browsers

# Notes
I am able to go to his trooper page without issue when accessing it from any of the rosters, just not from the promotion board.

**Comment by Soyvolon** [comment]
Eligible for promotion links are directed to the account ID and not the users Birth Number preventing user display page from loading.
