### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by jdoxley** [501stLegionA3/FiveOhFirstDataCore#346]
Add a navigation bar for the site.

**Comment by hobnob11** [comment]
Issues in testing:
- Requires a hard refresh (ctrl + F5) for changes to actually apply
- `+` Appears next to all entries, even those without sub-entries
- Requires double-clicking to select an existing nav-bar item to edit, bug? or just different UX from the rest of the site
- Manual save button in contrast to how the rest of the site works, again UX confusion.
