### ISSUE TITLE
Update Data core for “Initial Class” entry

### ISSUE THREAD

**Issue by ieatbacon20** [501stLegionA3/FiveOhFirstDataCore#349]
Web Page 501st Data Core Trooper info

With the merge of BCT/PIT and UTC creating Phase White we no longer keep track of Initial or Private Cycle# and Class# want to suggest to simply remove “Initial Training”. All previous Documents of Initial Cycle and Classes have been archived 

if need further explanation feel free to DM CX-C Bacon Discord: ieatbacon#2026

**Comment by Soyvolon** [comment]
Wont be working on this - not critical and the data core rework fixes all of these problems anyways.
