### ISSUE TITLE
Data Core - Recruit Promotion options

### ISSUE THREAD

**Issue by Dadecoy** [501stLegionA3/FiveOhFirstDataCore#350]
# Describe the bug
As Mynock NCOIC unable to Promote a CR to CR-C

# To Reproduce
1. Go to https://dc.501stlegion-a3.com/
2. Click on Mynock
3. Scroll down to Command Promotion Board
4. Scroll down to the Bottom of the Page
5. Type in Lyss into the search box
6. Click on recruit and Click on the Second Box. 
7. See error

# Expected behavior
An Option to promote a CR in Mynock to the rank of Cadet then to trooper.

# Screenshots

![501datacore_sectionpromo](https://user-images.githubusercontent.com/90737106/151875808-1aae7320-a82b-486d-ad6a-ffb5e01828d6.png)

# Platform
Google Chrome

# Notes
Any other notes go here.

**Comment by Dadecoy** [comment]
![Datacorerecuritpromo](https://user-images.githubusercontent.com/90737106/151876222-5f20e10d-fd22-4e5c-b350-986ebf792585.png)
Sorry Attached the wrong Picture

**Comment by Soyvolon** [comment]
Intentionally behavior
