### ISSUE TITLE
Admin Access keeps being lost

### ISSUE THREAD

**Issue by hobnob11** [501stLegionA3/FiveOhFirstDataCore#374]
# Describe the bug
I can no longer access any of the admin pages, despite logging out and logging in, closing the tab and reopening it, etc. 
This has happened multiple times, reliability issue? 

# To Reproduce
1. Log in
2. Try to access any admin page i.e /admin
3. "You do not have permission to access this page"

# Expected behavior
Access to da page 

# Screenshots
![image](https://user-images.githubusercontent.com/2287055/157538336-7fb5076a-6c50-463c-a0c4-cd31c2169706.png)

**Comment by Soyvolon** [comment]
Updates to other policies remove the access from the admin policy.
