### ISSUE TITLE
Add "Placed Roster" sorting for all columns

### ISSUE THREAD

**Issue by Kushiban501st** [501stLegionA3/FiveOhFirstDataCore#40]
# Description
In the "Placed Roster" page, add the possibility to sort by any of the columns.

# Details
Add the same sorting arrow there is for "Birth #" to all columns

# Page Design
If you are not asking for a page - skip this.
What do you want the page to look like? Are there any images, tables, etc. How is it organized?

# Notes
Any additional notes go here.

**Comment by Soyvolon** [comment]
Additionally sorting needs to be case-insensitive for text input fields.
