### ISSUE TITLE
Document New Recruiter Pages

### ISSUE THREAD

**Issue by Soyvolon** [501stLegionA3/FiveOhFirstDataCore#79]
# Pages Changed
- New Recruit Form
- Unregistered Troopers

# Detailed Changes
- New Recruit Form
    - Added two new buttons and a new field to select a preferred role.
- Unregistered Troopers
    - Added columns for all added fields on the new recruit form

**Comment by Soyvolon** [comment]
![image](https://user-images.githubusercontent.com/16871668/125220054-09a86480-e294-11eb-8eac-05da4636c575.png)
![image](https://user-images.githubusercontent.com/16871668/125220069-12993600-e294-11eb-8a2e-01a2b1e9b6aa.png)

**Comment by Zulu-87351** [comment]
Scheduled for 7/15/21
