### ISSUE TITLE
Document Edit Trooper Additons

### ISSUE THREAD

**Issue by Soyvolon** [501stLegionA3/FiveOhFirstDataCore#80]
# Pages Changed
- Edit Trooper Form

# Detailed Changes
- Added Military Police option directly above the additional details section.

**Comment by Soyvolon** [comment]
![image](https://user-images.githubusercontent.com/16871668/125220017-fa291b80-e293-11eb-852e-84ff3aaa85ee.png)

**Comment by Zulu-87351** [comment]
Scheduled for 7/15/21
