### ISSUE TITLE
Update Login Documentation

### ISSUE THREAD

**Issue by Soyvolon** [501stLegionA3/FiveOhFirstDataCore#83]
# Pages Changed
- All pages with a sidebar and login bar

# Detailed Changes
- All pages with a sidebar and login bar
    - The login options are now on the right side (top on mobile)
    - Login bar at the top has been removed
    - Login/Logout/Settings buttons are in a dropdown.

**Comment by Zulu-87351** [comment]
Scheduled 7/15/21

**Comment by Zulu-87351** [comment]
Pages Affected: Account Registration
